Metrics/BlockLength:
  Max: 20
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 160
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 20

Documentation:
  Enabled: false

Rails/Output:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - db/migrate/*.rb
    - db/schema.rb
    - spec/*.rb
    - config/**/*
    - bin/**/*
    - test/**/*
    - config.ru
    - Rakefile
